# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

# project
cmake_minimum_required(VERSION 3.15.0)
cmake_policy(SET CMP0091 NEW)
project(webview LANGUAGES CXX C)

# target
add_library(webview SHARED "")
set_target_properties(webview PROPERTIES OUTPUT_NAME "webview")
set_target_properties(webview PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/build/windows/x64/release")
set_target_properties(webview PROPERTIES ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_SOURCE_DIR}/build/windows/x64/release")
target_include_directories(webview SYSTEM PRIVATE
    C:/Users/guest_blmsaex/AppData/Local/.xmake/packages/w/webview/@default/10253c39aca14760ae4382272800b680/include
    C:/Users/guest_blmsaex/AppData/Local/.xmake/packages/m/mswebview2/1.0.2151.40/05ebbfa15464411d8dd899f0f2506b71/include
)
target_compile_definitions(webview PRIVATE
    WEBVIEW_BUILD_SHARED
    WEBVIEW_API=__declspec(dllexport)
)
target_compile_options(webview PRIVATE
    $<$<COMPILE_LANGUAGE:CXX>:/EHsc>
)
if(MSVC)
    target_compile_options(webview PRIVATE /EHsc)
else()
    target_compile_options(webview PRIVATE -fcxx-exceptions)
endif()
set_target_properties(webview PROPERTIES CXX_EXTENSIONS OFF)
target_compile_features(webview PRIVATE cxx_std_17)
if(MSVC)
    target_compile_options(webview PRIVATE nil)
else()
    target_compile_options(webview PRIVATE -O1)
endif()
if(MSVC)
    set_property(TARGET webview PROPERTY
        MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
endif()
target_link_libraries(webview PRIVATE
    kernel32
    ntdll
)
target_sources(webview PRIVATE
    src/webview.cpp
)